"""add fundi_marked_done to jobs

Revision ID: 3293611f7f59
Revises: 7d70c1d238ed
Create Date: 2026-06-29 13:57:03.113634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3293611f7f59'
down_revision: Union[str, None] = '7d70c1d238ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'jobs', 'fundi_profiles', ['fundi_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    # ### end Alembic commands ###
