"""add fundi_id to jobs

Revision ID: 7d70c1d238ed
Revises: f6e12ce0f4e6
Create Date: 2026-06-28 21:40:37.122584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d70c1d238ed'
down_revision: Union[str, None] = 'f6e12ce0f4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('fundi_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'fundi_profiles', ['fundi_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'fundi_id')
    # ### end Alembic commands ###
